In [2]:
import cv2
import os
from keras.models import load_model
import numpy as np
from pygame import mixer
import datetime 

mixer.init()
sound = mixer.Sound('alarm.wav')

face = cv2.CascadeClassifier('haar cascade files\haarcascade_frontalface_alt.xml')
leye = cv2.CascadeClassifier('haar cascade files\haarcascade_lefteye_2splits.xml')
reye = cv2.CascadeClassifier('haar cascade files\haarcascade_righteye_2splits.xml')



lbl=['Closed','Open']

model = load_model('models/cnnCat2.h5')
path = os.getcwd()
cap = cv2.VideoCapture(0)
font = cv2.FONT_HERSHEY_COMPLEX_SMALL
count=0
Time=0
thicc=2
rpred=[99]
lpred=[99]

while(True):
    ret, frame = cap.read()
    height,width = frame.shape[:2] 

    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    
    faces = face.detectMultiScale(gray,minNeighbors=5,scaleFactor=1.1,minSize=(25,25))
    left_eye = leye.detectMultiScale(gray)
    right_eye =  reye.detectMultiScale(gray)

    cv2.rectangle(frame, (0,height-50) , (200,height) , (0,0,0) , thickness=cv2.FILLED )

    for (x,y,w,h) in faces:
        cv2.rectangle(frame, (x,y) , (x+w,y+h) , (100,100,100) , 1 )

    for (x,y,w,h) in right_eye:
        r_eye=frame[y:y+h,x:x+w]
        count=count+1
        r_eye = cv2.cvtColor(r_eye,cv2.COLOR_BGR2GRAY)
        r_eye = cv2.resize(r_eye,(24,24))
        r_eye= r_eye/255
        r_eye=  r_eye.reshape(24,24,-1)
        r_eye = np.expand_dims(r_eye,axis=0)
        #rpred = model.predict_classes(r_eye)
        predict_x = model.predict(r_eye)
        print(predict_x)
        rpred = np.argmax(predict_x,axis=1)
        print(rpred)
        #print(rpred)
        if(rpred[0]==1):
            lbl='Open' 
        if(rpred[0]==0):
            lbl='Closed'
        break

    for (x,y,w,h) in left_eye:
        l_eye=frame[y:y+h,x:x+w]
        count=count+1
        l_eye = cv2.cvtColor(l_eye,cv2.COLOR_BGR2GRAY)  
        l_eye = cv2.resize(l_eye,(24,24))
        l_eye= l_eye/255
        l_eye=l_eye.reshape(24,24,-1)
        l_eye = np.expand_dims(l_eye,axis=0)
        #lpred = model.predict_classes(l_eye)
        predict_x = model.predict(l_eye)
        lpred = np.argmax(predict_x,axis=1)
        if(lpred[0]==1):
            lbl='Open'   
        if(lpred[0]==0):
            lbl='Closed'
        break
        
    dt = str(datetime.datetime.now()) 
    cv2.putText(frame,dt,(290,height-20), font, 1,(255,255,255),1,cv2.LINE_AA)     

    if(rpred[0]==0 and lpred[0]==0):
        Time=Time+1
        cv2.putText(frame,"Closed",(10,height-20), font, 1,(255,255,255),1,cv2.LINE_AA)
    # if(rpred[0]==1 or lpred[0]==1):
    else:
        Time=Time-1
        cv2.putText(frame,"Open",(10,height-20), font, 1,(255,255,255),1,cv2.LINE_AA)
        
    dt = str(datetime.datetime.now()) 
    cv2.putText(frame,dt,(1200,height-20), font, 1,(255,255,255),1,cv2.LINE_AA)    
    if(Time<0):
        Time=0   
    cv2.putText(frame,'Time:'+str(Time),(100,height-20), font, 1,(255,255,255),1,cv2.LINE_AA)
    if(Time>5):
        #person is feeling sleepy so we beep the alarm
        cv2.imwrite(os.path.join(path,'image.jpg'),frame)
        try:
            sound.play()
            
        except:  # isplaying = False
            pass
        if(thicc<16):
            thicc= thicc+2
        else:
            thicc=thicc-2
            if(thicc<2):
                thicc=2
        cv2.rectangle(frame,(0,0),(width,height),(0,0,255),thicc)
    if(Time>10):
        cv2.putText(frame,"MESSAGE SENT",(200,height-400),font,1,(0,255,0),1,cv2.LINE_AA)
        if(thicc<16):
            thicc= thicc+2
        else:
            thicc=thicc-2
            if(thicc<2):
                thicc=2
        cv2.rectangle(frame,(0,0),(width,height),(0,0,255),thicc)
        
    cv2.imshow('Drowsey Detection',frame)
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break
        
        
cap.release()
cv2.destroyAllWindows()


C:\Users\Himaja\anaconda3\nandu\lib\site-packages\scipy\__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.23.0
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"



pygame 2.5.2 (SDL 2.28.3, Python 3.9.7)
Hello from the pygame community. https://www.pygame.org/contribute.html


1/1 [==============================] - 5s 5s/step
[[0.42304274 0.5769572 ]]
[1]
1/1 [==============================] - 0s 56ms/step
[[1.4886743e-04 9.9985111e-01]]
[1]
1/1 [==============================] - 0s 44ms/step
[[0.00166741 0.99833256]]
[1]
1/1 [==============================] - 0s 42ms/step
[[0.03538158 0.9646184 ]]
[1]
1/1 [==============================] - 0s 49ms/step
[[0.20139691 0.79860306]]
[1]
1/1 [==============================] - 0s 105ms/step
[[0.03894899 0.96105105]]
[1]
1/1 [==============================] - 0s 93ms/step
[[0.10807041 0.8919296 ]]
[1]
1/1 [==============================] - 0s 50ms/step
[[0.03509459 0.96490544]]
[1]
1/1 [==============================] - 0s 45ms/step
[[0.08076088 0.91923916]]
[1]
1/1 [==============================] - 0s 42ms/step
[[0.0260482 0.9739518]]
[1]
1/1 [==============================] - 0s 51ms/step
[[0.095067

1/1 [==============================] - 0s 42ms/step
[[0.02510841 0.9748916 ]]
[1]
1/1 [==============================] - 0s 43ms/step
[[0.00823173 0.99176824]]
[1]
1/1 [==============================] - 0s 40ms/step
[[0.00384352 0.9961565 ]]
[1]
1/1 [==============================] - 0s 55ms/step
[[0.4337517  0.56624836]]
[1]
1/1 [==============================] - 0s 44ms/step
[[0.8519544  0.14804561]]
[0]
1/1 [==============================] - 0s 58ms/step
[[0.85433483 0.1456652 ]]
[0]
1/1 [==============================] - 0s 50ms/step
[[0.5971085  0.40289152]]
[0]
1/1 [==============================] - 0s 53ms/step
[[0.75367206 0.24632794]]
[0]
1/1 [==============================] - 0s 53ms/step
[[0.4862221 0.5137779]]
[1]
1/1 [==============================] - 0s 45ms/step
[[0.4858346 0.5141654]]
[1]
1/1 [==============================] - 0s 78ms/step
[[0.69894695 0.3010531 ]]
[0]
1/1 [==============================] - 0s 61ms/step
[[0.86171407 0.1382859 ]]
[0]
1/1 [===============

1/1 [==============================] - 0s 53ms/step
[[0.00797804 0.9920219 ]]
[1]
1/1 [==============================] - 0s 54ms/step
[[0.04488436 0.9551157 ]]
[1]
1/1 [==============================] - 0s 60ms/step
[[0.02363562 0.9763643 ]]
[1]
1/1 [==============================] - 0s 60ms/step
[[0.00483911 0.9951609 ]]
[1]
1/1 [==============================] - 0s 54ms/step
[[0.04072144 0.9592786 ]]
[1]
1/1 [==============================] - 0s 61ms/step
[[0.24718785 0.7528122 ]]
[1]
1/1 [==============================] - 0s 50ms/step
[[0.2819994 0.7180006]]
[1]
1/1 [==============================] - 0s 46ms/step
[[0.13690695 0.863093  ]]
[1]
1/1 [==============================] - 0s 47ms/step
[[0.99309665 0.00690333]]
[0]
1/1 [==============================] - 0s 41ms/step
[[0.12992401 0.870076  ]]
[1]
1/1 [==============================] - 0s 53ms/step
[[0.1051349  0.89486516]]
[1]
1/1 [==============================] - 0s 53ms/step
[[0.438628  0.5613719]]
[1]
1/1 [===============

1/1 [==============================] - 0s 49ms/step
[[0.02683042 0.97316957]]
[1]
1/1 [==============================] - 0s 45ms/step
[[0.3375961  0.66240394]]
[1]
1/1 [==============================] - 0s 43ms/step
[[0.08790196 0.9120981 ]]
[1]
1/1 [==============================] - 0s 41ms/step
[[0.02229881 0.9777012 ]]
[1]
1/1 [==============================] - 0s 63ms/step
[[0.09448124 0.9055188 ]]
[1]
1/1 [==============================] - 0s 54ms/step
[[0.15088749 0.84911245]]
[1]
1/1 [==============================] - 0s 58ms/step
[[0.15338983 0.8466102 ]]
[1]
1/1 [==============================] - 0s 64ms/step
[[0.06421337 0.93578666]]
[1]
1/1 [==============================] - 0s 82ms/step
[[0.05952486 0.94047517]]
[1]
1/1 [==============================] - 0s 88ms/step
[[0.04677283 0.95322716]]
[1]
1/1 [==============================] - 0s 44ms/step
[[0.05140637 0.9485936 ]]
[1]
1/1 [==============================] - 0s 46ms/step
[[0.18114051 0.8188595 ]]
[1]
1/1 [===========

1/1 [==============================] - 0s 45ms/step
[[0.00772435 0.99227566]]
[1]
1/1 [==============================] - 0s 45ms/step
[[0.01777185 0.9822282 ]]
[1]
1/1 [==============================] - 0s 44ms/step
[[0.01076611 0.98923385]]
[1]
1/1 [==============================] - 0s 54ms/step
[[0.00291239 0.99708766]]
[1]
1/1 [==============================] - 0s 49ms/step
[[0.05086936 0.9491306 ]]
[1]
1/1 [==============================] - 0s 43ms/step
[[0.03342656 0.9665735 ]]
[1]
1/1 [==============================] - 0s 53ms/step
[[0.01631639 0.98368365]]
[1]
1/1 [==============================] - 0s 102ms/step
[[0.00359851 0.99640155]]
[1]
1/1 [==============================] - 0s 41ms/step
[[0.9830723  0.01692765]]
[0]
1/1 [==============================] - 0s 48ms/step
[[0.11924202 0.8807579 ]]
[1]
1/1 [==============================] - 0s 42ms/step
[[0.01177546 0.9882245 ]]
[1]
1/1 [==============================] - 0s 41ms/step
[[0.01159992 0.9884001 ]]
[1]
1/1 [==========

1/1 [==============================] - 0s 49ms/step
[[9.9932241e-01 6.7760877e-04]]
[0]
1/1 [==============================] - 0s 42ms/step
[[0.8738651  0.12613486]]
[0]
1/1 [==============================] - 0s 51ms/step
[[0.5434332 0.4565668]]
[0]
1/1 [==============================] - 0s 39ms/step
[[0.868493   0.13150696]]
[0]
1/1 [==============================] - 0s 49ms/step
[[0.59903574 0.40096426]]
[0]
1/1 [==============================] - 0s 41ms/step
[[0.05293067 0.94706935]]
[1]
1/1 [==============================] - 0s 47ms/step
[[0.04903964 0.9509604 ]]
[1]
1/1 [==============================] - 0s 58ms/step
[[0.01776429 0.98223567]]
[1]
1/1 [==============================] - 0s 44ms/step
[[0.00673449 0.9932655 ]]
[1]
1/1 [==============================] - 0s 41ms/step
[[0.0560481 0.9439519]]
[1]
1/1 [==============================] - 0s 58ms/step
[[0.00642379 0.9935762 ]]
[1]
1/1 [==============================] - 0s 50ms/step
[[0.00765318 0.99234676]]
[1]
1/1 [=========

1/1 [==============================] - 0s 41ms/step
[[0.9925724  0.00742751]]
[0]
1/1 [==============================] - 0s 41ms/step
[[0.9942894  0.00571062]]
[0]
1/1 [==============================] - 0s 40ms/step
[[0.9911186  0.00888136]]
[0]
1/1 [==============================] - 0s 41ms/step
[[9.990736e-01 9.263270e-04]]
[0]
1/1 [==============================] - 0s 71ms/step
[[0.9988475  0.00115253]]
[0]
1/1 [==============================] - 0s 44ms/step
[[0.99342513 0.00657483]]
[0]
1/1 [==============================] - 0s 41ms/step
[[0.97257453 0.02742551]]
[0]
1/1 [==============================] - 0s 40ms/step
[[0.9901564  0.00984365]]
[0]
1/1 [==============================] - 0s 50ms/step
[[0.9962943  0.00370561]]
[0]
1/1 [==============================] - 0s 50ms/step
[[0.9810781  0.01892187]]
[0]
1/1 [==============================] - 0s 58ms/step
[[0.9936522  0.00634781]]
[0]
1/1 [==============================] - 0s 44ms/step
[[0.99610126 0.00389878]]
[0]
1/1 [=======

In [4]:
import cv2 as cv
img=cv.imread()
cv.imshow(nandu,img)

TypeError: imread() missing required argument 'filename' (pos 1)

In [2]:
import tensorflow as ts

RuntimeError: module compiled against API version 0x10 but this version of numpy is 0xf

SystemError: initialization of _pywrap_checkpoint_reader raised unreported exception

In [3]:
pip install tensorflow

  Attempting uninstall: numpy
    Found existing installation: numpy 1.22.4
    Uninstalling numpy-1.22.4:
      Successfully uninstalled numpy-1.22.4



ERROR: Could not install packages due to an OSError: [WinError 5] Access is denied: 'C:\\Users\\Himaja\\anaconda3\\nandu\\Lib\\site-packages\\~1mpy\\.libs\\libopenblas.EL2C6PLE4ZYW3ECEVIV3OXXGRN2NRFM2.gfortran-win_amd64.dll'
Consider using the `--user` option or check the permissions.



In [1]:
import numpy as np

In [2]:
pip install keras

Note: you may need to restart the kernel to use updated packages.


In [1]:
import numpy as np
np.__version__

'1.23.0'

In [1]:
print('hii')

hii


In [3]:
pip install numpy==1.23.0

  Using cached numpy-1.23.0-cp39-cp39-win_amd64.whl (14.7 MB)
Note: you may need to restart the kernel to use updated packages.


ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
daal4py 2021.3.0 requires daal==2021.2.3, which is not installed.
tensorflow-intel 2.15.0 requires numpy<2.0.0,>=1.23.5, but you have numpy 1.23.0 which is incompatible.
scipy 1.7.1 requires numpy<1.23.0,>=1.16.5, but you have numpy 1.23.0 which is incompatible.
numba 0.54.1 requires numpy<1.21,>=1.17, but you have numpy 1.23.0 which is incompatible.


In [2]:
print('hii')

hii


In [2]:
pip install opencv-python

Note: you may need to restart the kernel to use updated packages.


In [10]:
#[20:03, 3/9/2024] Akhila @ ECE @ G7: import cv2
import os
from keras.models import load_model
import numpy as np
from pygame import mixer
import time

from twilio.rest import Client
from geopy.geocoders import Nominatim

# Twilio Configuration
account_sid = 'ACc8e5a16fb96a16db0c32f22ce3db8ad1'
auth_token = '0789b6ef246f08f18822b088dfeee19e'
client = Client(account_sid, auth_token)
from_number = '+18145243614'
to_number = '+919513012552'                                                                                     

mixer.init()
sound = mixer.Sound('alarm.wav')

face = cv2.CascadeClassifier('haar cascade files\haarcascade_frontalface_alt.xml')
leye = cv2.CascadeClassifier('haar cascade files\haarcascade_lefteye_2splits.xml')
reye = cv2.CascadeClassifier('haar cascade files\haarcascade_righteye_2splits.xml')



lbl=['Close','Open']

model = load_model('models/cnnCat2.h5')
path = os.getcwd()
cap = cv2.VideoCapture(0)
font = cv2.FONT_HERSHEY_COMPLEX_SMALL
count=0
score=0
thicc=2
rpred=[99]
lpred=[99]

geolocator = Nominatim(user_agent="Drowsiness Detection")  # Initialize geopy geolocator

def send_sms(body):
    message = client.messages.create(
        body=body,
        from_=from_number,
        to=to_number
    )
    print("SMS Sent")

def get_location():
    # Get the live location
    lat = 0.0  # Replace with actual latitude
    lon = 0.0  # Replace with actual longitude
    location = geolocator.reverse(f"{lat}, {lon}")
    return location

start_alarm_time = None
start_sms_time = None
sms_counter = 0  # Counter to limit the number of SMS messages

# Variable to track the previous score
prev_score = 0


while(True):
    ret, frame = cap.read()
    height,width = frame.shape[:2] 

    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    
    faces = face.detectMultiScale(gray,minNeighbors=5,scaleFactor=1.1,minSize=(25,25))
    left_eye = leye.detectMultiScale(gray)
    right_eye =  reye.detectMultiScale(gray)

    cv2.rectangle(frame, (0,height-50) , (200,height) , (0,0,0) , thickness=cv2.FILLED )

    for (x,y,w,h) in faces:
        cv2.rectangle(frame, (x,y) , (x+w,y+h) , (100,100,100) , 1 )

    for (x,y,w,h) in right_eye:
        r_eye=frame[y:y+h,x:x+w]
        count=count+1
        r_eye = cv2.cvtColor(r_eye,cv2.COLOR_BGR2GRAY)
        r_eye = cv2.resize(r_eye,(24,24))
        r_eye= r_eye/255
        r_eye=  r_eye.reshape(24,24,-1)
        r_eye = np.expand_dims(r_eye,axis=0)
        #rpred = model.predict_classes(r_eye)
        predict_x = model.predict(r_eye)
        print(predict_x)
        rpred = np.argmax(predict_x,axis=1)
        print(rpred)
        #print(rpred)
        if(rpred[0]==1):
            lbl='Open' 
        if(rpred[0]==0):
            lbl='Closed'
        break

    for (x,y,w,h) in left_eye:
        l_eye=frame[y:y+h,x:x+w]
        count=count+1
        l_eye = cv2.cvtColor(l_eye,cv2.COLOR_BGR2GRAY)  
        l_eye = cv2.resize(l_eye,(24,24))
        l_eye= l_eye/255
        l_eye=l_eye.reshape(24,24,-1)
        l_eye = np.expand_dims(l_eye,axis=0)
        #lpred = model.predict_classes(l_eye)
        predict_x = model.predict(l_eye)
        lpred = np.argmax(predict_x,axis=1)
        if(lpred[0]==1):
            lbl='Open'   
        if(lpred[0]==0):
            lbl='Closed'
        break

    if(rpred[0]==0 and lpred[0]==0):
        score=score+1
        cv2.putText(frame,"Closed",(10,height-20), font, 1,(255,255,255),1,cv2.LINE_AA)
    # if(rpred[0]==1 or lpred[0]==1):
    else:
        score=score-1
        cv2.putText(frame,"Open",(10,height-20), font, 1,(255,255,255),1,cv2.LINE_AA)
    
        
    if(score<0):
        score=0   
    cv2.putText(frame,'Score:'+str(score),(100,height-20), font, 1,(255,255,255),1,cv2.LINE_AA)
    if(score>5):
        #person is feeling sleepy so we beep the alarm
        cv2.imwrite(os.path.join(path,'image.jpg'),frame)
        try:
            sound.play()
            
        except:  # isplaying = False
            pass
        if(thicc<16):
            thicc= thicc+2
        else:
            thicc=thicc-2
            if(thicc<2):
                thicc=2
        cv2.rectangle(frame,(0,0),(width,height),(0,0,255),thicc) 
    if prev_score <= 20 and score > 20 and sms_counter < 3:
        try:
            location = get_location()  # Fetch live location
            send_sms(f'The driver seems drowsy. Please check. Location: {location}')  # Send SMS with live location
            start_sms_time = time.time()
            sms_counter += 1
            print('message')
        except Exception as e:
            print("Error:", e)
    
    # Check for score transitions (decreased to below 10 and then increased to 20 again)
    if prev_score > 10 and score <= 10 and sms_counter < 3:
        sms_counter = 0  # Reset SMS counter
        start_sms_time = None  # Reset SMS timer
    
    # Update previous score
    prev_score = score
    cv2.imshow('frame',frame)
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break
cap.release()
cv2.destroyAllWindows()


1/1 [==============================] - 0s 140ms/step
[[4.0642291e-04 9.9959356e-01]]
[1]
1/1 [==============================] - 0s 41ms/step
[[0.00120981 0.9987902 ]]
[1]
1/1 [==============================] - 0s 48ms/step
[[0.00118062 0.9988193 ]]
[1]
1/1 [==============================] - 0s 42ms/step
[[0.00376699 0.99623305]]
[1]
1/1 [==============================] - 0s 40ms/step
[[0.0036176  0.99638236]]
[1]
1/1 [==============================] - 0s 39ms/step
[[0.00908451 0.9909155 ]]
[1]
1/1 [==============================] - 0s 40ms/step
[[0.0186838 0.9813162]]
[1]
1/1 [==============================] - 0s 38ms/step
[[0.01564396 0.984356  ]]
[1]
1/1 [==============================] - 0s 42ms/step
[[9.990170e-01 9.829416e-04]]
[0]
1/1 [==============================] - 0s 40ms/step
[[0.9913483  0.00865171]]
[0]
1/1 [==============================] - 0s 48ms/step
[[9.992889e-01 7.110613e-04]]
[0]
1/1 [==============================] - 0s 41ms/step
[[0.9977704 0.0022296]]
[0]
1/1 [

1/1 [==============================] - 0s 57ms/step
[[0.28466603 0.715334  ]]
[1]
1/1 [==============================] - 0s 60ms/step
[[0.00686228 0.9931377 ]]
[1]
1/1 [==============================] - 0s 43ms/step
[[0.542569   0.45743102]]
[0]
1/1 [==============================] - 0s 50ms/step
[[0.10945049 0.89054954]]
[1]
1/1 [==============================] - 0s 53ms/step
[[0.02614276 0.9738573 ]]
[1]
1/1 [==============================] - 0s 57ms/step
[[0.20549291 0.79450715]]
[1]
1/1 [==============================] - 0s 41ms/step
[[0.01897356 0.9810265 ]]
[1]
1/1 [==============================] - 0s 50ms/step
[[1.3573286e-04 9.9986422e-01]]
[1]
1/1 [==============================] - 0s 52ms/step
[[3.176614e-04 9.996823e-01]]
[1]
1/1 [==============================] - 0s 39ms/step
[[0.00224473 0.99775535]]
[1]
1/1 [==============================] - 0s 42ms/step
[[0.0074576 0.9925424]]
[1]
1/1 [==============================] - 0s 38ms/step
[[1.981537e-05 9.999802e-01]]
[1]
1/1 

1/1 [==============================] - 0s 42ms/step
[[0.1416561 0.8583439]]
[1]
1/1 [==============================] - 0s 53ms/step
[[0.00312531 0.9968747 ]]
[1]
1/1 [==============================] - 0s 37ms/step
[[0.01829513 0.98170483]]
[1]
1/1 [==============================] - 0s 39ms/step
[[0.10961068 0.8903893 ]]
[1]
1/1 [==============================] - 0s 47ms/step
[[0.01430078 0.98569924]]
[1]
1/1 [==============================] - 0s 40ms/step
[[0.07874036 0.92125964]]
[1]
1/1 [==============================] - 0s 40ms/step
[[0.007674 0.992326]]
[1]
1/1 [==============================] - 0s 54ms/step
[[0.02191838 0.97808164]]
[1]
1/1 [==============================] - 0s 38ms/step
[[0.37828976 0.6217103 ]]
[1]


In [8]:
pip install geopy